### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments

### ISSUE THREAD

**Issue by coxy17** [divengine/div-ajax-mapping#3]
I receive the following error when testing

_Fatal error: Uncaught ArgumentCountError: Too few arguments to function divengine\ajaxmap::__construct(), 0 passed in C:\wamp\www\teststuff\divengine-ajaxmap\test.php on line 24 and exactly 1 expected in C:\wamp\www\teststuff\divengine-ajaxmap\vendor\divengine\ajaxmap\src\ajaxmap.php on line 52_

php file
```
use divengine\ajaxmap;
require __DIR__ . '/vendor/autoload.php';

function sum($x, $y){
  return $x + $y; 
}

class Enterprise{
  public static function getEmployees(){
      return [
        ["name" => "Thomas Hardy", "salary" => 1500],  
        ["name" => "Christina Berglund", "salary" => 1200] 
      ];  
    } 
}

// Server instance ...

$server = new ajaxmap(); 

// ... Add methods ...

$server->addMethod("sum"); 
$server->addClass("Enterprise"); 

// ... and go!
$server->go(); 
```

html

```
<!DOCTYPE html>
<html>
<head>
<title>Divengine Ajaxmap</title>
<meta name="viewport" content="width=device-width, user-scalable=no">
</head>
<body>

<h1>Test Ajaxmap</h1>

<script type="text/javascript" src="http://localhost/teststuff/divengine-ajaxmap/vendor/divengine/ajaxmap/ajaxmap.js"></script>
<script type="text/javascript">
    var map = new ajaxmap("test.php");
    var sum = map.sum(20, 10);
  
	
	console.log(sum);

</script>

</body>
</html>
```

_Originally posted by @coxy17 in https://github.com/divengine/ajaxmap/issues/2#issuecomment-2307732851_

**Comment by rafageist** [comment]
Hello

Until version 1.2 it was mandatory to pass the $name parameter through the constructor. Now in version 1.3 it is optional. You can update the dependencies and try again.

Best Regards

**Comment by coxy17** [comment]
ok, i have updated to the latest version and its working now. I'll test more later on but do you know why i cant update it via composer? i have not got a version set in the composer.json file.

**Comment by coxy17** [comment]
just an update when i go to use page to run it i get the following outputted in the browser, when running $server->go(); 

`{ sum: function(x,y, async){ var params = {};params.x = x;params.y = y; return (new ajaxmap()).call(this.__server, 'sum',params); } ,Enterprise: { getEmployees: function(){ var params = {}; return (new ajaxmap()).call(this.__server, 'Enterprise::getEmployees',params); } } }`

**Comment by coxy17** [comment]
its ok i had not updated the old version correctly in composer, its is working now. I had to update the package manually as composer would not grab the latest version, any ideas why? any help appreciated. I can update all other repositories just fine, not sure why i cant update ajaxmap.

composer require divengine/ajaxmap "1.3.0" returns invalid version

**Comment by rafageist** [comment]
@coxy17 Please try again, I had to update the package manually in Packagist

**Comment by coxy17** [comment]
@rafageist thanks, that worked! Also just out of curiosity, why is the PHP minimum version 8.2 for this project? I noticed it went from 5.4 to 8.2 in the latest update.

**Comment by rafageist** [comment]
Hi. Glad it worked for you!

About your curiosity, in this version I started using the new PHP features like typed parameters. So I can't leave version 5. And why put 7 if I can put PHP version 8? The idea is to move everything forward.

Regards
